language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install qtdeclarative5-dev

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*"

notifications:
email: false
